<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\currencies_list\Services\CurrenciesApiService;

function currencies_list_help(string $route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.currencies_list':
            $output = "<h3>" . t('Currencies list module help') . "</h3>";
            return $output;
        default:
    }
}

function currencies_list_cron() {
    CurrenciesApiService::updateRates();
}